#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n helved get secret azuread-helved-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: utsjekk-lokal
  namespace: helved
  labels:
    team: helved
spec:
  claims:
    groups:
      - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir tilgang til prosessering
      - id: "97140b9a-07c5-414c-beeb-69824d04c044" # 0000-GA-Dagpenger-Prosessering-Admin gir tilgang til prosessering
  preAuthorizedApplications:
    - application: utsjekk-lokal
      cluster: dev-gcp
      namespace: helved
  replyUrls:
    - url: "http://localhost:8000/auth/openid/callback"
  logoutUrl: "http://localhost:8000"
  tenant: trygdeetaten.no
  secretName: azuread-helved-lokal