apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-iverksett
  namespace: teamdagpenger
  labels:
    team: teamdagpenger

spec:
  image: {{ image }}
  ingresses:
      - {{ ingress }}
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 100m
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: {{ kafka.pool }}
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{ springProfil }}
    - name: PROSESSERING_GRUPPE
      value: {{ groups.prosesseringAdmin }}
    - name: DAGPENGER_SAKSBEHANDLER_GRUPPE
      value: {{ groups.saksbehandlerDagpenger }}
    - name: DAGPENGER_BESLUTTER_GRUPPE
      value: {{ groups.beslutterDagpenger }}
    - name: TILTAKSPENGER_SAKSBEHANDLER_GRUPPE
      value: {{ groups.saksbehandlerTiltakspenger }}
    - name: TILTAKSPENGER_BESLUTTER_GRUPPE
      value: {{ groups.beslutterTiltakspenger }}
    - name: TILLEGGSSTONADER_BESLUTTER_GRUPPE
      value: {{ groups.beslutterTilleggsstønader }}
  envFrom:
    - secret: {{ unleash.apiToken }}
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: {{ groups.prosesseringAdmin }} # 0000-GA-Dagpenger-Prosessering-Admin gir tilgang til prosessering
          - id: {{ groups.saksbehandlerDagpenger }} # 0000-GA-Dagpenger-Saksbehandler
          - id: {{ groups.beslutterDagpenger }} # 0000-GA-Dagpenger-Beslutter
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: dp-iverksett # For å sette i gang grensesnittavstemming første gang
        - application: dp-vedtak-iverksett
        - application: dp-prosessering #frontend for task-rammeverket
        - application: dp-behandling
        - application: tiltakspenger-utbetaling
          namespace: tpts
        - application: tilleggsstonader-sak
          namespace: tilleggsstonader
    outbound:
      rules:
        - application: dp-oppdrag
      external:
        - host: dagpenger-unleash-api.nav.cloud.nais.io
  gcp:
    sqlInstances:
      - type: {{ db.version }} # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: {{ db.tier }}
        cascadingDelete: false
        highAvailability: {{ db.highAvailability }}
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: {{ db.name }}
            envVarPrefix: DB
