apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: iverksetting-status-v1
  namespace: helved
  labels:
    team: helved
spec:
  pool: {{ kafka.pool }}
  acl:
    - team: helved
      application: utsjekk
      access: readwrite