apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: iverksetting-status-v1
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: {{ kafka.pool }}
  acl:
    - team: teamdagpenger
      application: dp-iverksett
      access: readwrite