apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: {{unleash.apiToken}}
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: dagpenger
  secretName: {{unleash.apiToken}}

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{unleash.environment}}