name: Configure topic

on:
  push:
    branches:
      - main
    paths:
      - '.deploy/topic.yaml'
      - '.github/workflows/configure-topic.yaml'

jobs:
  applyDev:
    name: Apply dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/topic.yaml
          VARS: .deploy/vars-preprod.yaml

  applyProd:
    name: Apply prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/docker-build-push@v0
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .deploy/topic.yaml
          VARS: .deploy/vars-prod.yaml