name: Build-Deploy prod
on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'docs'
      - 'dependabot/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  CI: true
  TZ: Europe/Oslo

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read/save maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-dp-iverksett-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-dp-iverksett-
            ${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Bygg med Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${IMAGE} .
          docker push ${IMAGE}

  deploy-dev:
    name: Deploy til dev-gcp
    timeout-minutes: 30
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        timeout-minutes: 30
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/unleash-apitoken.yaml,.deploy/nais.yaml
          VARS: .deploy/vars-preprod.yaml

  deploy-prod:
    name: Deploy til prod-gcp
    timeout-minutes: 30
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        timeout-minutes: 30
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/unleash-apitoken.yaml,.deploy/nais.yaml
          VARS: .deploy/vars-prod.yaml
